// 
// Decompiled by Procyon v0.5.36
// 

package br.uerj.calc.ui;

import java.awt.Image;
import java.awt.Component;
import javax.swing.JScrollPane;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.Point;
import javax.swing.JTextArea;
import java.awt.Container;
import javax.swing.JFrame;

public class help extends JFrame
{
    private Container cp;
    private JTextArea areaTexto;
    
    help(final Point pontoMain) {
        super("Ajuda para Calc-X 1.0");
        final Image iconeAjuda = Toolkit.getDefaultToolkit().getImage(this.getClass().getClassLoader().getResource("img/ajuda.gif"));
        this.setIconImage(iconeAjuda);
        this.setLocation(0, 0);
        this.setSize(340, 420);
        this.setResizable(false);
        this.cp = this.getContentPane();
        (this.areaTexto = new JTextArea()).setEditable(false);
        this.areaTexto.setFont(new Font("Courier", 0, 12));
        final JScrollPane scrollPane = new JScrollPane(this.areaTexto, 22, 30);
        this.areaTexto.append("        ** Ajuda para Calc-X 1.0 **\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ** Bot\u00f5es especiais:\n");
        this.areaTexto.append(" CE - Limpa as vari\u00e1veis da Calculadora,\n");
        this.areaTexto.append("      mant\u00e9m o que est\u00e1 na mem\u00f3ria, e a\n");
        this.areaTexto.append("      fun\u00e7\u00e3o F(x).\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" AC - Limpa todas as vari\u00e1veis, inclusive \n");
        this.areaTexto.append("      mem\u00f3ria, fun\u00e7\u00e3o F(x) e express\u00e3o.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" M+ - \u00c9 um acumulador soma o valor que est\u00e1\n");
        this.areaTexto.append("      na tela ao que j\u00e1 est\u00e1 na mem\u00f3ria. \n");
        this.areaTexto.append("      Ele come\u00e7a zerado.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" RM - Recupera o valor que est\u00e1 na \n");
        this.areaTexto.append("      mem\u00f3ria, sem apag\u00e1-la.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" << - Backspace.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" = - No seu uso fora da express\u00e3o, faz uma\n");
        this.areaTexto.append("     opera\u00e7\u00e3o com dois operandos. \n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" REL - Abre e fecha a janela de Relat\u00f3rio \n");
        this.areaTexto.append("       dos c\u00e1lculos.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Expres - Muda o modo da calculadora para\n");
        this.areaTexto.append("          a entrada de uma express\u00e3o, que\n");
        this.areaTexto.append("          n\u00e3o precisa ser totalmente \n");
        this.areaTexto.append("          prentisada.Ex: 4+sen(40+5)*(3/2)\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Fun\u00e7\u00e3o - Muda o modo da calculadora para\n");
        this.areaTexto.append("          a entrada de uma fun\u00e7\u00e3o F(x), \n");
        this.areaTexto.append("          habilitando os bot\u00f5es de Ra\u00edz,\n");
        this.areaTexto.append("          Deriv, e Integ.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ** Bot\u00f5es de operadores: \n");
        this.areaTexto.append(" (Em ordem de Preced\u00eancia)\n");
        this.areaTexto.append(" sen - Seno\n");
        this.areaTexto.append(" cos - Cosseno\n");
        this.areaTexto.append(" tan - Tangente \n");
        this.areaTexto.append(" ArcSen - Arco Seno\n");
        this.areaTexto.append(" ArcCos - Arco Cosseno\n");
        this.areaTexto.append(" ArcTan - Arco Tangente\n");
        this.areaTexto.append(" LN - Logaritmo Neperiano\n");
        this.areaTexto.append(" x^y - valor de x elevado a y\n");
        this.areaTexto.append(" x^(1/2) - Ra\u00edz quadrada\n");
        this.areaTexto.append(" / - Divis\u00e3o\n");
        this.areaTexto.append(" * - Multiplica\u00e7\u00e3o\n");
        this.areaTexto.append(" - - Subtra\u00e7\u00e3o\n");
        this.areaTexto.append(" + - Soma\n");
        this.areaTexto.append(" Dependendo do modo de Opera\u00e7\u00e3o (Fun\u00e7\u00e3o,\n");
        this.areaTexto.append(" Express\u00e3o ou Normal) esses bot\u00f5es \n");
        this.areaTexto.append(" realizam fun\u00e7\u00f5es diferentes.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ** Outros:\n");
        this.areaTexto.append(" Deg - Graus (normal, padr\u00e3o)\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Rad - Radiano\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" EXP - Nota\u00e7\u00e3o cient\u00edfica no formato:\n");
        this.areaTexto.append("       nE(+/-)Num\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ** Constantes:\n");
        this.areaTexto.append(" e  -  N\u00famero de Euler\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" PI - Valor de PI\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" x  - habilitado apenas no modo fun\u00e7\u00e3o\n");
        this.areaTexto.append("      para indicar a inc\u00f3gnita.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ),( - habilitado apenas para parentisar\n");
        this.areaTexto.append("       fun\u00e7\u00f5es e express\u00f5es.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ** Bot\u00f5es de Fun\u00e7\u00e3o:\n");
        this.areaTexto.append(" F(x) - Calcula F(x) para x dado.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Ra\u00edz - Acha o valor aproximado da \n");
        this.areaTexto.append("        primeira ra\u00edz no intervalo\n");
        this.areaTexto.append("        fornecido.Precis\u00e3o de 1E-14 ou\n");
        this.areaTexto.append("        10^(-14). \n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Deriv - Acha o valor aproximado da \n");
        this.areaTexto.append("         derivada da fun\u00e7\u00e3o no valor dado.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Integ - Acha o valor aproximado da \n");
        this.areaTexto.append("         integral no intervalo fornecido.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ENT - Entra com o valor que est\u00e1 na tela.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ** Bot\u00f5es da Express\u00e3o:\n");
        this.areaTexto.append(" ENT - Resolve apenas a Express\u00e3o.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" = - Resolve a express\u00e3o e efetua, o\n");
        this.areaTexto.append("     resultado da express\u00e3o com algum \n");
        this.areaTexto.append("     operador anterior.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Obs: O sinal de menos (-) \u00e9 sempre\n");
        this.areaTexto.append(" considerado operador para express\u00f5es e\n");
        this.areaTexto.append(" fun\u00e7\u00f5es, n\u00e3o existindo n\u00fameros negativos.\n");
        this.areaTexto.append(" Exemplo: Se voc\u00ea deseja digitar a fun\u00e7\u00e3o\n");
        this.areaTexto.append(" F(x) = -x/(-3)*5, ela deve ser escrita \n");
        this.areaTexto.append(" como F(x) = (0-x)/(0-3)*5.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ** Bot\u00f5es do Relat\u00f3rio:\n");
        this.areaTexto.append(" Salvar - Quando pressionado a primeira\n");
        this.areaTexto.append("          vez Abre uma janela de di\u00e1logo\n");
        this.areaTexto.append("          para slecionar o lugar onde \n");
        this.areaTexto.append("          o relat\u00f3rio deve ser salvo.\n");
        this.areaTexto.append("          Em vezes posteriores (sem que se\n");
        this.areaTexto.append("          tenha fechado a janela ou \n");
        this.areaTexto.append("          clicado no bot\u00e3o limpar) ele \n");
        this.areaTexto.append("          salva o arquivo no lugar j\u00e1\n");
        this.areaTexto.append("          escolhido.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Limpar - Limpa o conte\u00fado do relat\u00f3rio.\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Obs: O formato salvo \u00e9 o txt, n\u00e3o \n");
        this.areaTexto.append(" havendo necessidade de se colocar a \n");
        this.areaTexto.append(" extens\u00e3o do arquivo na hora de salv\u00e1-lo.   \n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" ** Atalhos do Teclado:\n");
        this.areaTexto.append(" F1 - Conte\u00fado de Ajuda\n");
        this.areaTexto.append(" F2 - Sobre\n");
        this.areaTexto.append(" F3 - Expres\n");
        this.areaTexto.append(" F4 - Fun\u00e7\u00e3o\n");
        this.areaTexto.append(" F5 - EXP\n");
        this.areaTexto.append(" F6 - REL\n");
        this.areaTexto.append(" F7 - Salvar\n");
        this.areaTexto.append(" F8 - Limpar\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" Esc - AC\n");
        this.areaTexto.append(" Delete - CE\n");
        this.areaTexto.append(" End - ENT\n");
        this.areaTexto.append(" Enter - = (igual)\n");
        this.areaTexto.append(" Backspace - <<\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" A - Alterna entre Deg e Rad\n");
        this.areaTexto.append(" S - sen\n");
        this.areaTexto.append(" C - cos\n");
        this.areaTexto.append(" T - tan\n");
        this.areaTexto.append(" V - x^(1/2)\n");
        this.areaTexto.append(" L - LN\n");
        this.areaTexto.append(" y - x^y\n");
        this.areaTexto.append(" [ - ArcSen\n");
        this.areaTexto.append(" ] - ArcCos\n");
        this.areaTexto.append(" \\ - ArcTan\n");
        this.areaTexto.append(" Z - +/-\n");
        this.areaTexto.append(" M - M+\n");
        this.areaTexto.append(" N - RM\n");
        this.areaTexto.append(" E - e\n");
        this.areaTexto.append(" P - PI\n");
        this.areaTexto.append(" ( - (\n");
        this.areaTexto.append(" ) - )\n");
        this.areaTexto.append(" X - x\n");
        this.areaTexto.append(" F - F(x)\n");
        this.areaTexto.append(" R - Ra\u00edz\n");
        this.areaTexto.append(" D - Deriv\n");
        this.areaTexto.append(" I - Integ\n");
        this.areaTexto.append("\n");
        this.areaTexto.append(" +,-,/,*,.,1,2,3,4,5,6,7,8,9,0\n");
        this.areaTexto.append(" Exercem suas fun\u00e7\u00f5es normais.\n");
        this.areaTexto.setCaretPosition(0);
        this.cp.add(scrollPane);
    }
}
